import 'package:flutter/material.dart';
import 'dart:convert';
import 'package:printing/printing.dart';
import '../../core/network/api_client.dart';
import '../orders/order_detail_page.dart';
import '../products/products_page.dart';
import '../customers/customers_page.dart';

class DashboardPage extends StatefulWidget {
  const DashboardPage({super.key, required this.storeName, required this.client});
  final String storeName;
  final ApiClient client;
  @override State<DashboardPage> createState()=>_DashboardPageState();
}
class _DashboardPageState extends State<DashboardPage>{ late Future<List<dynamic>> orders; int? busyOrder; bool batchBusy=false; final Set<int> selected={}; List<dynamic> visibleOrders=[]; @override void initState(){super.initState();orders=widget.client.orders();}
  Future<void> _print(List<String> ids,String type)async{final result=await widget.client.shipmentPdf(ids,type:type);await Printing.sharePdf(bytes:base64Decode(result['content_base64'] as String),filename:result['filename'] as String);}
  Future<void> _ship(int orderId)async{setState(()=>busyOrder=orderId);try{final result=await widget.client.registerShipment(orderId,{});final raw=result['entries'];final entries=raw is Map?Map<String,dynamic>.from(raw):<String,dynamic>{};if(!mounted){return;}await showDialog(context:context,builder:(context)=>AlertDialog(title:const Text('مرسوله ثبت شد'),content:Text('کد رهگیری: ${entries['barcode']??'از تاپین دریافت نشد'}'),actions:[if(entries['id']!=null)TextButton(onPressed:()=>_print([entries['id'].toString()],'label'),child:const Text('لیبل PDF')),if(entries['order_id']!=null)TextButton(onPressed:()=>_print([entries['order_id'].toString()],'invoice'),child:const Text('فاکتور PDF')),TextButton(onPressed:()=>Navigator.pop(context),child:const Text('بستن'))]));setState(()=>orders=widget.client.orders());}catch(e){if(mounted){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('ثبت مرسوله انجام نشد: $e')));}}finally{if(mounted){setState(()=>busyOrder=null);}}}
  Future<void> _registerSelected()async{setState(()=>batchBusy=true);final failures=<String>[];for(final item in visibleOrders.where((o)=>selected.contains((o['id'] as num).toInt())&&o['tapin_order_id']==null)){try{await widget.client.registerShipment((item['id'] as num).toInt(),{});}catch(e){failures.add('#${item['id']}: $e');}}if(!mounted){return;}setState((){batchBusy=false;selected.clear();orders=widget.client.orders();});ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(failures.isEmpty?'مرسوله‌های انتخابی با موفقیت ثبت شدند.':'برخی سفارش‌ها ثبت نشدند:\n${failures.join('\n')}')));}
  Future<void> _printSelected(String type)async{final key=type=='label'?'tapin_uuid':'tapin_order_id';final ids=visibleOrders.where((o)=>selected.contains((o['id'] as num).toInt())&&o[key]!=null).map((o)=>o[key].toString()).toList();if(ids.isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('سفارش انتخابی دارای مرسوله ثبت‌شده نیست.')));return;}setState(()=>batchBusy=true);try{await _print(ids,type);}finally{if(mounted){setState(()=>batchBusy=false);}}}
  @override Widget build(BuildContext context) => Scaffold(
    appBar: AppBar(title: Text(widget.storeName),actions:[IconButton(onPressed:()=>setState(()=>orders=widget.client.orders()),icon:const Icon(Icons.refresh_rounded))]),
    body: FutureBuilder<List<dynamic>>(future:orders,builder:(context,snapshot){if(snapshot.connectionState!=ConnectionState.done){return const Center(child:CircularProgressIndicator());}if(snapshot.hasError){return _Error(message:snapshot.error.toString(),retry:()=>setState(()=>orders=widget.client.orders()));}final list=snapshot.data??[];visibleOrders=list;final processing=list.where((o)=>o['status']=='processing').length;return ListView(padding:const EdgeInsets.all(16),children:[
      Text('مرکز عملیات',style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:12),
      GridView.count(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisCount:2,mainAxisSpacing:12,crossAxisSpacing:12,childAspectRatio:1.45,children:[
        _Stat(title:'آخرین سفارش‌ها',value:'${list.length}',icon:Icons.receipt_long_rounded),_Stat(title:'در حال انجام',value:'$processing',icon:Icons.local_shipping_outlined),
      ]),const SizedBox(height:22),
      Text('سفارش‌های واقعی',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w700)),const SizedBox(height:10),
      if(selected.isNotEmpty)Card(child:Padding(padding:const EdgeInsets.all(12),child:Wrap(spacing:8,runSpacing:8,children:[FilledButton.icon(onPressed:batchBusy?null:_registerSelected,icon:const Icon(Icons.local_shipping_outlined),label:Text('ثبت ${selected.length} سفارش')),OutlinedButton.icon(onPressed:batchBusy?null:()=>_printSelected('label'),icon:const Icon(Icons.qr_code_rounded),label:const Text('لیبل گروهی PDF')),OutlinedButton.icon(onPressed:batchBusy?null:()=>_printSelected('invoice'),icon:const Icon(Icons.print_outlined),label:const Text('فاکتور گروهی PDF')),TextButton(onPressed:batchBusy?null:()=>setState(selected.clear),child:const Text('لغو انتخاب'))]))),
      if(list.isEmpty)const Card(child:Padding(padding:EdgeInsets.all(24),child:Text('سفارشی در ووکامرس وجود ندارد.',textAlign:TextAlign.center))) else ...list.map((o){final id=(o['id'] as num).toInt();final registered=o['tapin_order_id']!=null;return Card(child:ListTile(onTap:()async{await Navigator.push(context,MaterialPageRoute(builder:(_)=>OrderDetailPage(orderId:id,client:widget.client)));if(mounted)setState(()=>orders=widget.client.orders());},leading:Checkbox(value:selected.contains(id),onChanged:(value)=>setState(()=>value==true?selected.add(id):selected.remove(id))),title:Text('سفارش #$id'),subtitle:Text('${o['customer']} • ${o['status']}\n${o['total']} ${o['currency']}${registered?'\nرهگیری: ${o['tracking_number']??'در انتظار بارکد'}':''}'),isThreeLine:true,trailing:busyOrder==id?const SizedBox.square(dimension:22,child:CircularProgressIndicator(strokeWidth:2)):registered?const Icon(Icons.chevron_left_rounded):IconButton(tooltip:'ثبت واقعی در تاپین',onPressed:()=>_ship(id),icon:const Icon(Icons.local_shipping_outlined))));}),
    ]);}),
    bottomNavigationBar:NavigationBar(selectedIndex:0,onDestinationSelected:(index){if(index==2)Navigator.push(context,MaterialPageRoute(builder:(_)=>ProductsPage(client:widget.client)));if(index==3)Navigator.push(context,MaterialPageRoute(builder:(_)=>CustomersPage(client:widget.client)));},destinations:const [NavigationDestination(icon:Icon(Icons.dashboard_outlined),selectedIcon:Icon(Icons.dashboard_rounded),label:'خانه'),NavigationDestination(icon:Icon(Icons.receipt_long_outlined),label:'سفارش‌ها'),NavigationDestination(icon:Icon(Icons.inventory_2_outlined),label:'محصولات'),NavigationDestination(icon:Icon(Icons.people_outline_rounded),label:'مشتریان')]),
  );
}
class _Stat extends StatelessWidget { const _Stat({required this.title,required this.value,required this.icon});final String title,value;final IconData icon;@override Widget build(BuildContext context)=>Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Icon(icon),Text(value,style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w800)),Text(title)])));}
class _Error extends StatelessWidget{const _Error({required this.message,required this.retry});final String message;final VoidCallback retry;@override Widget build(BuildContext context)=>Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.cloud_off_rounded,size:44),const SizedBox(height:12),Text(message,textAlign:TextAlign.center),const SizedBox(height:16),FilledButton(onPressed:retry,child:const Text('تلاش دوباره'))])));}
