import 'package:flutter/material.dart';
import '../../core/network/api_client.dart';
import '../orders/order_detail_page.dart';

class CustomerDetailPage extends StatefulWidget{const CustomerDetailPage({super.key,required this.client,required this.customerId});final ApiClient client;final int customerId;@override State<CustomerDetailPage> createState()=>_CustomerDetailPageState();}
class _CustomerDetailPageState extends State<CustomerDetailPage>{late Future<Map<String,dynamic>> future;bool saving=false,filled=false;final first=TextEditingController(),last=TextEditingController(),email=TextEditingController(),phone=TextEditingController(),billingAddress=TextEditingController(),billingCity=TextEditingController(),billingState=TextEditingController(),billingPostcode=TextEditingController(),shippingAddress=TextEditingController(),shippingCity=TextEditingController(),shippingState=TextEditingController(),shippingPostcode=TextEditingController();@override void initState(){super.initState();future=widget.client.customer(widget.customerId);}@override void dispose(){for(final c in [first,last,email,phone,billingAddress,billingCity,billingState,billingPostcode,shippingAddress,shippingCity,shippingState,shippingPostcode]){c.dispose();}super.dispose();}
  void fill(Map<String,dynamic> c){if(filled)return;filled=true;final b=Map<String,dynamic>.from(c['billing'] as Map? ?? const {}),s=Map<String,dynamic>.from(c['shipping'] as Map? ?? const {});first.text='${c['first_name']??''}';last.text='${c['last_name']??''}';email.text='${c['email']??''}';phone.text='${b['phone']??''}';billingAddress.text='${b['address_1']??''}';billingCity.text='${b['city']??''}';billingState.text='${b['state']??''}';billingPostcode.text='${b['postcode']??''}';shippingAddress.text='${s['address_1']??''}';shippingCity.text='${s['city']??''}';shippingState.text='${s['state']??''}';shippingPostcode.text='${s['postcode']??''}';}
  Future<void> save()async{setState(()=>saving=true);try{final result=await widget.client.updateCustomer(widget.customerId,{'first_name':first.text.trim(),'last_name':last.text.trim(),'email':email.text.trim(),'billing':{'first_name':first.text.trim(),'last_name':last.text.trim(),'email':email.text.trim(),'phone':phone.text.trim(),'address_1':billingAddress.text.trim(),'city':billingCity.text.trim(),'state':billingState.text.trim(),'postcode':billingPostcode.text.trim()},'shipping':{'first_name':first.text.trim(),'last_name':last.text.trim(),'address_1':shippingAddress.text.trim(),'city':shippingCity.text.trim(),'state':shippingState.text.trim(),'postcode':shippingPostcode.text.trim()}});if(!mounted)return;setState(()=>future=Future.value(result));ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('اطلاعات مشتری در ووکامرس ذخیره شد.')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('ذخیره انجام نشد: $e')));}finally{if(mounted)setState(()=>saving=false);}}
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text('مشتری #${widget.customerId}'),actions:[FilledButton(onPressed:saving?null:save,child:const Text('ذخیره'))]),body:FutureBuilder<Map<String,dynamic>>(future:future,builder:(context,snapshot){if(snapshot.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(snapshot.hasError)return Center(child:Text(snapshot.error.toString()));final c=snapshot.data!;fill(c);final orders=c['orders'] as List? ?? const [];return ListView(padding:const EdgeInsets.all(16),children:[if(saving)const LinearProgressIndicator(),_Section(title:'آمار واقعی خرید',child:Row(children:[Expanded(child:_Stat(label:'تعداد سفارش',value:'${c['orders_count']}')),Expanded(child:_Stat(label:'مجموع خرید',value:'${c['total_spent']}'))])),_Section(title:'پروفایل',child:Column(children:[Row(children:[Expanded(child:TextField(controller:first,decoration:const InputDecoration(labelText:'نام'))),const SizedBox(width:8),Expanded(child:TextField(controller:last,decoration:const InputDecoration(labelText:'نام خانوادگی')))]),TextField(controller:email,keyboardType:TextInputType.emailAddress,decoration:const InputDecoration(labelText:'ایمیل')),TextField(controller:phone,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'شماره موبایل'))])),_Section(title:'آدرس صورتحساب',child:_address(billingAddress,billingCity,billingState,billingPostcode)),_Section(title:'آدرس ارسال',child:_address(shippingAddress,shippingCity,shippingState,shippingPostcode)),_Section(title:'سفارش‌های مشتری',child:orders.isEmpty?const Text('این مشتری سفارشی ندارد.'):Column(children:orders.map((raw){final o=Map<String,dynamic>.from(raw as Map);return ListTile(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>OrderDetailPage(orderId:(o['id'] as num).toInt(),client:widget.client))),contentPadding:EdgeInsets.zero,title:Text('سفارش #${o['number']}'),subtitle:Text('${o['status']}  •  ${o['date']??''}'),trailing:Text('${o['total']} ${o['currency']}'));}).toList()))]);}));
  Widget _address(TextEditingController address,TextEditingController city,TextEditingController state,TextEditingController postcode)=>Column(children:[TextField(controller:address,decoration:const InputDecoration(labelText:'نشانی')),Row(children:[Expanded(child:TextField(controller:state,decoration:const InputDecoration(labelText:'استان'))),const SizedBox(width:8),Expanded(child:TextField(controller:city,decoration:const InputDecoration(labelText:'شهر')))]),TextField(controller:postcode,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'کد پستی'))]);}
class _Section extends StatelessWidget{const _Section({required this.title,required this.child});final String title;final Widget child;@override Widget build(BuildContext context)=>Card(margin:const EdgeInsets.only(bottom:12),child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(title,style:Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight:FontWeight.w700)),const SizedBox(height:12),child])));}
class _Stat extends StatelessWidget{const _Stat({required this.label,required this.value});final String label,value;@override Widget build(BuildContext context)=>Column(children:[Text(value,style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w800)),Text(label)]);}
