import 'package:flutter/material.dart';
import '../../core/network/api_client.dart';
import '../../core/theme/theme_controller.dart';

class WorkflowCenterPage extends StatelessWidget{
  const WorkflowCenterPage({super.key,required this.client});final ApiClient client;
  @override Widget build(BuildContext context)=>DefaultTabController(length:6,child:Scaffold(appBar:AppBar(title:const Text('عملیات حرفه‌ای'),bottom:const TabBar(isScrollable:true,tabs:[Tab(text:'سود واقعی'),Tab(text:'مرجوعی'),Tab(text:'صف خطا'),Tab(text:'تیم'),Tab(text:'تاریخچه'),Tab(text:'ظاهر و نسخه')])),body:TabBarView(children:[_Profit(client),_Returns(client),_Queue(client),_Team(client),_Audit(client),_Preferences(client)])));
}
class _Profit extends StatefulWidget{const _Profit(this.c);final ApiClient c;@override State<_Profit> createState()=>_ProfitState();}
class _ProfitState extends State<_Profit>{int days=30;late Future<Map<String,dynamic>> f;@override void initState(){super.initState();load();}void load()=>setState(()=>f=widget.c.profit(days:days));@override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(16),children:[SegmentedButton<int>(segments:const [ButtonSegment(value:7,label:Text('۷ روز')),ButtonSegment(value:30,label:Text('۳۰ روز')),ButtonSegment(value:90,label:Text('۹۰ روز'))],selected:{days},onSelectionChanged:(v){days=v.first;load();}),const SizedBox(height:12),FutureBuilder<Map<String,dynamic>>(future:f,builder:(context,s){if(!s.hasData)return const Center(child:Padding(padding:EdgeInsets.all(40),child:CircularProgressIndicator()));final d=s.data!;return GridView.count(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisCount:2,mainAxisSpacing:10,crossAxisSpacing:10,childAspectRatio:1.35,children:[_Metric('فروش','${d['revenue']} ${d['currency']}',Icons.payments_outlined),_Metric('بهای کالا','${d['product_cost']} ${d['currency']}',Icons.inventory_2_outlined),_Metric('ارسال و مرجوعی','${d['shipping']} + ${d['refunds']}',Icons.local_shipping_outlined),_Metric('سود واقعی','${d['profit']} ${d['currency']}',Icons.trending_up_rounded)]);})]);}
class _Returns extends StatefulWidget{const _Returns(this.c);final ApiClient c;@override State<_Returns> createState()=>_ReturnsState();}
class _ReturnsState extends State<_Returns>{late Future<List<dynamic>> f;@override void initState(){super.initState();load();}void load()=>setState(()=>f=widget.c.returns());Future<void> add()async{final order=TextEditingController(),reason=TextEditingController(),amount=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('مرجوعی جدید'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:order,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'شماره سفارش')),const SizedBox(height:8),TextField(controller:reason,decoration:const InputDecoration(labelText:'علت مرجوعی')),const SizedBox(height:8),TextField(controller:amount,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'مبلغ'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('انصراف')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('ثبت واقعی'))]));if(ok==true){await widget.c.createReturn({'order_id':int.tryParse(order.text),'reason':reason.text,'amount':amount.text});load();}}@override Widget build(BuildContext context)=>Scaffold(floatingActionButton:FloatingActionButton.extended(onPressed:add,icon:const Icon(Icons.add),label:const Text('مرجوعی')),body:_List(future:f,empty:'مرجوعی ثبت نشده است.',builder:(m)=>ListTile(title:Text('مرجوعی #${m['id']} • سفارش #${m['order_id']}'),subtitle:Text('${m['reason']}\nوضعیت: ${m['status']}'),trailing:PopupMenuButton<String>(onSelected:(v)async{await widget.c.updateReturn((m['id'] as num).toInt(),v);load();},itemBuilder:(_)=>const [PopupMenuItem(value:'received',child:Text('دریافت شد')),PopupMenuItem(value:'approved',child:Text('تأیید')),PopupMenuItem(value:'rejected',child:Text('رد')),PopupMenuItem(value:'refunded',child:Text('بازپرداخت شد')),PopupMenuItem(value:'exchanged',child:Text('تعویض شد'))]))));}
class _Queue extends StatefulWidget{const _Queue(this.c);final ApiClient c;@override State<_Queue> createState()=>_QueueState();}
class _QueueState extends State<_Queue>{late Future<Map<String,dynamic>> f;@override void initState(){super.initState();load();}void load()=>setState(()=>f=widget.c.retryQueue());@override Widget build(BuildContext context)=>Scaffold(floatingActionButton:FloatingActionButton.extended(onPressed:()async{await widget.c.retryQueue(retry:true);load();},icon:const Icon(Icons.replay),label:const Text('تلاش مجدد')),body:FutureBuilder<Map<String,dynamic>>(future:f,builder:(context,s)=>_MapList(data:s.data?['items'] as List?,loading:!s.hasData,empty:'صف عملیات ناموفق خالی است.',builder:(m)=>ListTile(title:Text('${m['type']} • سفارش #${m['order_id']??'-'}'),subtitle:Text('تلاش: ${m['attempts']}\n${m['last_error']}'))))); }
class _Team extends StatelessWidget{const _Team(this.c);final ApiClient c;@override Widget build(BuildContext context)=>_List(future:c.team(),empty:'کاربر عملیاتی وجود ندارد.',builder:(m)=>ListTile(leading:const CircleAvatar(child:Icon(Icons.person_outline)),title:Text('${m['name']}'),subtitle:Text((m['roles'] as List).join('، ')))) ;}
class _Audit extends StatelessWidget{const _Audit(this.c);final ApiClient c;@override Widget build(BuildContext context)=>_List(future:c.audit(),empty:'عملیاتی ثبت نشده است.',builder:(m)=>ListTile(leading:const Icon(Icons.history_rounded),title:Text('${m['message']}'),subtitle:Text('${m['created_at']} • ${(m['context'] as Map?)?['user_name']??'سیستم'}'))) ;}
class _Preferences extends StatefulWidget{const _Preferences(this.c);final ApiClient c;@override State<_Preferences> createState()=>_PreferencesState();}
class _PreferencesState extends State<_Preferences>{String theme='light';bool notify=true;Map<String,dynamic>? release;@override void initState(){super.initState();load();}Future<void> load()async{final p=await widget.c.preferences(),r=await widget.c.releaseInfo();if(mounted)setState((){theme=p['theme']=='dark'?'dark':'light';notify=p['notifications']!=false;release=r;ThemeController.set(theme);});}Future<void> save()async{await widget.c.savePreferences({'theme':theme,'color':'emerald','thermal_size':'10x15','notifications':notify});ThemeController.set(theme);}@override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(16),children:[Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(children:[DropdownButtonFormField<String>(value:theme,decoration:const InputDecoration(labelText:'حالت نمایش'),items:const [DropdownMenuItem(value:'light',child:Text('روشن (پیش‌فرض)')),DropdownMenuItem(value:'dark',child:Text('تاریک'))],onChanged:(v)=>setState(()=>theme=v!)),SwitchListTile(value:notify,onChanged:(v)=>setState(()=>notify=v),title:const Text('اعلان‌های عملیاتی')),FilledButton.icon(onPressed:save,icon:const Icon(Icons.save_outlined),label:const Text('ذخیره تنظیمات'))]))),const SizedBox(height:12),Card(child:ListTile(leading:const Icon(Icons.system_update_alt),title:Text('افزونه ${release?['plugin_version']??'...'}'),subtitle:Text('API ${release?['api_version']??'...'} • حداقل اپ ${release?['minimum_app_version']??'...'}'),trailing:Icon(release?['compatible']==true?Icons.verified_rounded:Icons.warning_rounded,color:release?['compatible']==true?Colors.green:Colors.orange))) ]);}
class _List extends StatelessWidget{const _List({required this.future,required this.empty,required this.builder});final Future<List<dynamic>> future;final String empty;final Widget Function(Map<String,dynamic>) builder;@override Widget build(BuildContext context)=>FutureBuilder<List<dynamic>>(future:future,builder:(context,s)=>_MapList(data:s.data,loading:!s.hasData,empty:empty,builder:builder));}
class _MapList extends StatelessWidget{const _MapList({required this.data,required this.loading,required this.empty,required this.builder});final List? data;final bool loading;final String empty;final Widget Function(Map<String,dynamic>) builder;@override Widget build(BuildContext context){if(loading)return const Center(child:CircularProgressIndicator());final items=data??const [];if(items.isEmpty)return Center(child:Text(empty));return ListView.separated(padding:const EdgeInsets.all(16),itemCount:items.length,separatorBuilder:(_,__)=>const SizedBox(height:8),itemBuilder:(_,i)=>Card(child:builder(Map<String,dynamic>.from(items[i] as Map))));}}
class _Metric extends StatelessWidget{const _Metric(this.title,this.value,this.icon);final String title,value;final IconData icon;@override Widget build(BuildContext context)=>Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Icon(icon),Text(value,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w800)),Text(title)])));}
