import 'package:flutter/material.dart';
import '../../core/network/api_client.dart';

class OrderDetailPage extends StatefulWidget {
  const OrderDetailPage({super.key, required this.orderId, required this.client});
  final int orderId;
  final ApiClient client;
  @override
  State<OrderDetailPage> createState() => _OrderDetailPageState();
}

class _OrderDetailPageState extends State<OrderDetailPage> {
  late Future<Map<String, dynamic>> _future;
  bool _busy = false;
  @override
  void initState() { super.initState(); _future = widget.client.order(widget.orderId); }
  void _reload() => setState(() => _future = widget.client.order(widget.orderId));
  Future<void> _run(Future<Map<String, dynamic>> Function() action) async { setState(() => _busy = true); try { final data = await action(); if (mounted) setState(() => _future = Future.value(data)); } catch (e) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('عملیات انجام نشد: $e'))); } finally { if (mounted) setState(() => _busy = false); } }
  Future<void> _addNote() async { final controller = TextEditingController(); bool customer = false; final ok = await showDialog<bool>(context: context, builder: (context) => StatefulBuilder(builder: (context, setModalState) => AlertDialog(title: const Text('یادداشت جدید'), content: Column(mainAxisSize: MainAxisSize.min, children: [TextField(controller: controller, minLines: 3, maxLines: 6, decoration: const InputDecoration(labelText: 'متن یادداشت')), CheckboxListTile(contentPadding: EdgeInsets.zero, value: customer, onChanged: (v) => setModalState(() => customer = v ?? false), title: const Text('برای مشتری قابل مشاهده باشد'))]), actions: [TextButton(onPressed: () => Navigator.pop(context, false), child: const Text('انصراف')), FilledButton(onPressed: () => Navigator.pop(context, true), child: const Text('ثبت'))]))); if (ok == true && controller.text.trim().isNotEmpty) await _run(() => widget.client.addOrderNote(widget.orderId, controller.text.trim(), customerNote: customer)); }
  Future<void> _refund(Map<String, dynamic> order) async { final max = double.tryParse('${order['refundable_amount'] ?? 0}') ?? 0; final amount = TextEditingController(text: max.toStringAsFixed(0)); final reason = TextEditingController(); bool payment = false, restock = false; final ok = await showDialog<bool>(context: context, builder: (context) => StatefulBuilder(builder: (context, setModalState) => AlertDialog(title: const Text('ثبت بازپرداخت واقعی'), content: Column(mainAxisSize: MainAxisSize.min, children: [Text('حداکثر مبلغ قابل بازپرداخت: $max ${order['currency']}'), TextField(controller: amount, keyboardType: const TextInputType.numberWithOptions(decimal: true), decoration: const InputDecoration(labelText: 'مبلغ')), TextField(controller: reason, decoration: const InputDecoration(labelText: 'دلیل بازپرداخت')), SwitchListTile(contentPadding: EdgeInsets.zero, value: payment, onChanged: (v) => setModalState(() => payment = v), title: const Text('بازپرداخت از درگاه پرداخت')), SwitchListTile(contentPadding: EdgeInsets.zero, value: restock, onChanged: (v) => setModalState(() => restock = v), title: const Text('بازگرداندن موجودی کالا'))]), actions: [TextButton(onPressed: () => Navigator.pop(context, false), child: const Text('انصراف')), FilledButton(onPressed: () => Navigator.pop(context, true), child: const Text('تأیید نهایی بازپرداخت'))]))); final value = double.tryParse(amount.text); if (ok == true && value != null && value > 0) await _run(() => widget.client.refundOrder(widget.orderId, amount: value, reason: reason.text.trim(), refundPayment: payment, restockItems: restock)); }
  @override
  Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: Text('سفارش #${widget.orderId}'), actions: [IconButton(onPressed: _busy ? null : _reload, icon: const Icon(Icons.refresh_rounded))]), body: FutureBuilder<Map<String, dynamic>>(future: _future, builder: (context, snapshot) { if (snapshot.connectionState != ConnectionState.done) return const Center(child: CircularProgressIndicator()); if (snapshot.hasError) return Center(child: FilledButton(onPressed: _reload, child: const Text('تلاش دوباره'))); final o = snapshot.data!; final items = (o['items'] as List? ?? const []); final history = (o['history'] as List? ?? const []); final refunds = (o['refunds'] as List? ?? const []); final shipping = Map<String, dynamic>.from(o['shipping'] as Map? ?? const {}); final billing = Map<String, dynamic>.from(o['billing'] as Map? ?? const {}); final shipment = Map<String, dynamic>.from(o['shipment'] as Map? ?? const {}); return ListView(padding: const EdgeInsets.all(16), children: [
    if (_busy) const LinearProgressIndicator(),
    _Section(title: 'وضعیت و مبلغ', child: Column(children: [DropdownButtonFormField<String>(value: o['status'] as String?, decoration: const InputDecoration(labelText: 'وضعیت سفارش'), items: (o['status_options'] as List? ?? const []).map((s) { final m = Map<String, dynamic>.from(s as Map); return DropdownMenuItem(value: m['value'].toString(), child: Text(m['label'].toString())); }).toList(), onChanged: _busy ? null : (value) { if (value != null && value != o['status']) _run(() => widget.client.updateOrderStatus(widget.orderId, value)); }), _row('جمع کل', '${o['total']} ${o['currency']}'), _row('هزینه ارسال', '${o['shipping_total']} ${o['currency']}'), _row('تخفیف', '${o['discount_total']} ${o['currency']}'), _row('بازپرداخت‌شده', '${o['total_refunded']} ${o['currency']}'), _row('روش پرداخت', '${o['payment_method'] ?? '-'}')])) ,
    _Section(title: 'محصولات سفارش', child: Column(children: items.map((raw) { final item = Map<String, dynamic>.from(raw as Map); return ListTile(contentPadding: EdgeInsets.zero, leading: item['image'] == null ? const Icon(Icons.inventory_2_outlined) : Image.network(item['image'].toString(), width: 48, height: 48, fit: BoxFit.cover), title: Text(item['name'].toString()), subtitle: Text('تعداد: ${item['quantity']}  •  SKU: ${item['sku'].toString().isEmpty ? '-' : item['sku']}'), trailing: Text('${item['total']} ${o['currency']}')); }).toList())),
    _Section(title: 'اطلاعات ارسال', child: Column(children: [_row('گیرنده', '${shipping['first_name'] ?? billing['first_name'] ?? ''} ${shipping['last_name'] ?? billing['last_name'] ?? ''}'), _row('تلفن', '${shipping['phone'] ?? billing['phone'] ?? '-'}'), _row('آدرس', _address(shipping, billing)), _row('روش ارسال', '${o['shipping_method'] ?? '-'}'), _row('شناسه تاپین', '${shipment['tapin_order_id'] ?? '-'}'), _row('کد رهگیری', '${shipment['tracking_number'] ?? '-'}')])) ,
    _Section(title: 'عملیات', child: Wrap(spacing: 8, runSpacing: 8, children: [FilledButton.icon(onPressed: _busy ? null : _addNote, icon: const Icon(Icons.note_add_outlined), label: const Text('افزودن یادداشت')), OutlinedButton.icon(onPressed: _busy || (double.tryParse('${o['refundable_amount'] ?? 0}') ?? 0) <= 0 ? null : () => _refund(o), icon: const Icon(Icons.currency_exchange_rounded), label: const Text('بازپرداخت'))])),
    if (refunds.isNotEmpty) _Section(title: 'بازپرداخت‌ها', child: Column(children: refunds.map((raw) { final r = Map<String, dynamic>.from(raw as Map); return ListTile(contentPadding: EdgeInsets.zero, title: Text('${r['amount']} ${o['currency']}'), subtitle: Text('${r['reason'] ?? ''}\n${r['date'] ?? ''}')); }).toList())),
    _Section(title: 'تاریخچه عملیات', child: history.isEmpty ? const Text('تاریخچه‌ای ثبت نشده است.') : Column(children: history.map((raw) { final h = Map<String, dynamic>.from(raw as Map); return ListTile(contentPadding: EdgeInsets.zero, leading: Icon(h['customer_note'] == true ? Icons.person_outline : Icons.settings_outlined), title: Text(h['content'].toString()), subtitle: Text('${h['date'] ?? ''}')); }).toList())),
  ]); }));
  Widget _row(String title, String value) => Padding(padding: const EdgeInsets.symmetric(vertical: 5), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Expanded(child: Text(title, style: const TextStyle(color: Colors.grey))), Expanded(flex: 2, child: Text(value))]));
  String _address(Map<String, dynamic> shipping, Map<String, dynamic> billing) { final source = (shipping['address_1']?.toString().isNotEmpty ?? false) ? shipping : billing; return [source['state'], source['city'], source['address_1'], source['address_2'], source['postcode']].where((v) => v != null && v.toString().isNotEmpty).join('، '); }
}

class _Section extends StatelessWidget { const _Section({required this.title, required this.child}); final String title; final Widget child; @override Widget build(BuildContext context) => Card(margin: const EdgeInsets.only(bottom: 12), child: Padding(padding: const EdgeInsets.all(16), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Text(title, style: Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w700)), const SizedBox(height: 12), child]))); }
