name: Flutter CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { channel: stable, cache: true }
      - run: flutter create --platforms=android --org=ir.sahand.woomanager .
      - run: flutter pub get
      - run: dart format lib test
      - run: flutter analyze --no-fatal-infos --no-fatal-warnings
      - run: flutter test
